### ISSUE TITLE
在两台服务器之间登录无法被验证

### ISSUE THREAD

**Issue by FrankHan052176** [MCUmbrella/CSLBungee-Server#3]
信息:两台服务器之间不是局域网关系而是通过公网连接,且都有公网ip,一台运行Bungee,一台运行paper-1.16.5,插件版本皆为最新.
截图:
![bungee截图](https://user-images.githubusercontent.com/48244729/128831523-897ac68d-9250-4a55-9b5b-d216687c4a61.png)
![paper截图](https://user-images.githubusercontent.com/48244729/128831553-6128225b-83e9-4fce-b26e-6adae1322051.png)
情况: 两台服务器之间无法连接,但局域网内可以连接

**Comment by FrankHan052176** [comment]
补充一句,但是在bungee内使用cslbs u指令玩家就可以变成登陆后的状态(也就是此时通讯正常),且两台机器的14514端口都开放了

**Comment by FrankHan052176** [comment]
emmmm.我用BungeeCord的插件消息频道实现了原本插件的功能并修复了我的问题,插件源码在我的主页里,自取,请标明出处,谢谢

**Comment by MCUmbrella** [comment]
CSLBungee系列插件目前只适用于运行在同一台机器的共享同一IP地址的群组服务器
https://github.com/MCUmbrella/CSLBungee-Client/blob/ac7595cceb2541eef08ac04a3c11a62b78ad0e26/src/vip/floatationdevice/mcumbrella/cslbungee/client/CSLBC.java#L28
